<?php
declare (strict_types=1);

namespace Ekyna\Component\Colissimo\Postage\Model;

use Ekyna\Component\Colissimo\Base;

/**
 * Class Addressee
 * @package Ekyna\Component\Colissimo
 * @author  Etienne Dauvergne <contact@ekyna.com>
 *
 * @property string  $addresseeParcelRef
 * @property bool    $codeBarForReference
 * @property string  $serviceInfo
 * @property Address $address
 */
class Addressee extends Base\Model\AbstractModel
{
    /**
     * @inheritdoc
     */
    public static function buildDefinition(Base\Definition\Definition $definition): void
    {
        $definition
            ->addField(new Base\Definition\AlphaNumeric('addresseeParcelRef', false, 17))
            ->addField(new Base\Definition\Boolean('codeBarForReference', false))
            ->addField(new Base\Definition\AlphaNumeric('serviceInfo', false, 17))
            // promotionCode
            ->addField(new Base\Definition\Model('address', false, Address::class));
    }

    /**
     * @inheritdoc
     */
    public function validate(string $prefix = null): void
    {
        parent::validate($prefix); // TODO: Change the autogenerated stub

        // TODO See page 30
    }
}
